import {Outfit} from "next/font/google";
import "./globals.css";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],weight:["400","500","600","700","800"]
});


export const metadata = {
  title: "QuickFix",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${outfit.variable} h-full antialiased`}
    >
      <body className={outfit.className}>{children}</body>
    </html>
  );
}
